# Generated by Django 6.0.1 on 2026-01-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_point', models.CharField(max_length=50)),
                ('deck', models.CharField(error_messages=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('passenger_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('total_meal_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='ticketbooking.booking')),
            ],
        ),
    ]
