# Generated by Django 6.0.1 on 2026-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('seat_number', models.CharField(max_length=10)),
                ('deck', models.CharField(max_length=10)),
                ('drop_point', models.CharField(max_length=50)),
                ('ticket_price', models.IntegerField()),
                ('meal_name', models.TextField(blank=True, null=True)),
                ('meal_quantity', models.TextField(blank=True, null=True)),
                ('meal_price', models.TextField(blank=True, null=True)),
                ('total_meal_price', models.IntegerField(default=0)),
                ('grand_total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealorder',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='MealOrder',
        ),
    ]
