# Generated by Django 6.0.1 on 2026-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0002_ticketbooking_remove_mealorder_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
