# Generated by Django 6.0.1 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0003_alter_ticketbooking_meal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
