# Generated by Django 6.0.1 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0004_alter_ticketbooking_meal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
