# Generated by Django 6.0.1 on 2026-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0005_alter_ticketbooking_meal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_price',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
