# Generated by Django 6.0.1 on 2026-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0006_alter_ticketbooking_meal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
