# Generated by Django 6.0.1 on 2026-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0007_alter_ticketbooking_meal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='meal_quantity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
